# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beans', models.CharField(max_length=20)),
                ('roast', models.CharField(max_length=20)),
                ('syrup', models.CharField(max_length=20)),
                ('powder', models.CharField(max_length=20)),
                ('espresso', models.IntegerField()),
                ('foam', models.BooleanField(default=False)),
                ('milk', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('extra', models.TextField()),
                ('name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
