# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Powder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Syrup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='espresso',
        ),
        migrations.AddField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='coffee',
            name='shot',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='beans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Bean'),
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='powder',
        ),
        migrations.AlterField(
            model_name='coffee',
            name='roast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Roast'),
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='syrup',
        ),
        migrations.AddField(
            model_name='coffee',
            name='powder',
            field=models.ManyToManyField(to='menu.Powder'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='syrup',
            field=models.ManyToManyField(to='menu.Syrup'),
        ),
    ]
